[project]
name = "kefar"
version = "0.1.0"
description = ""
authors = [
    {name = "Natanael Arndt",email = "arndtn@gmail.com"}
]
license = "EUPL-1.2"
requires-python = "<4.0,>=3.11"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "jinja-rdf (>=0.1.11,<0.2.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "rdflib (>=7.6.0,<8.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "mkdocs (>=1.6.1,<2.0.0)",
    "mkrdf (>=0.2.4,<0.3.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "ruff (>=0.16.6,<0.17.0)"
]

[project.entry-points."mkdocs.plugins"]
mkrdf = "mkrdf:MkRDFPlugin"